[plugins]

# Plugin manager
"rocks.nvim" = "2.43.1"
"rocks-config.nvim" = "3.1.0"
"rocks-treesitter.nvim" = "1.3.0"
"rocks-git.nvim" = "2.5.2"

# Find all the things
"telescope.nvim" = "scm"

# Generate docstrings
neogen = "2.20.0"

# Various utility mini-plugins
"mini.nvim" = "0.15.0"

# The best git UI
neogit = "2.0.0"

# LSP
 
## Language server management
nvim-lspconfig = "2.1.0"
"mason.nvim" = "2.0.0"

## Better UI for LSP actions
"dressing.nvim" = "3.1.1"

# Automatic indentation
"guess-indent.nvim" = "scm"

# Best task runner
"overseer.nvim" = "1.5.0"

# Treesitter parsers
tree-sitter-astro = "0.0.33"
tree-sitter-bash = "0.0.40"
tree-sitter-bibtex = "0.0.29"
tree-sitter-comment = "0.0.29"
tree-sitter-css = "0.0.36"
tree-sitter-csv = "0.0.29"
tree-sitter-dart = "0.0.34"
tree-sitter-desktop = "0.0.8"
tree-sitter-dockerfile = "0.0.30"
tree-sitter-editorconfig = "0.0.47"
tree-sitter-eex = "0.0.29"
tree-sitter-elixir = "0.0.39"
tree-sitter-fish = "0.0.30"
tree-sitter-gitcommit = "0.0.33"
tree-sitter-git_config = "0.0.29"
tree-sitter-gitignore = "0.0.29"
tree-sitter-glsl = "0.0.30"
tree-sitter-go = "0.0.39"
tree-sitter-gomod = "0.0.33"
tree-sitter-heex = "0.0.34"
tree-sitter-ini = "0.0.29"
tree-sitter-java = "0.0.40"
tree-sitter-javascript = "0.0.36"
tree-sitter-jsdoc = "0.0.35"
tree-sitter-json = "0.0.36"
tree-sitter-jsonc = "0.0.29"
tree-sitter-julia = "0.0.41"
tree-sitter-just = "0.0.36"
tree-sitter-make = "0.0.29"
tree-sitter-markdown = "0.0.37"
tree-sitter-markdown_inline = "0.0.37"
tree-sitter-nginx = "0.0.30"
tree-sitter-php = "0.0.38"
tree-sitter-phpdoc = "0.0.30"
tree-sitter-po = "0.0.29"
tree-sitter-python = "0.0.40"
tree-sitter-rst = "0.0.32"
tree-sitter-smali = "0.0.29"
tree-sitter-sql = "0.0.39"
tree-sitter-templ = "0.0.45"
tree-sitter-toml = "0.0.31"
tree-sitter-typescript = "0.0.36"
tree-sitter-udev = "0.0.30"
tree-sitter-vue = "0.0.29"
tree-sitter-xml = "0.0.36"
tree-sitter-yaml = "0.0.31"

# Track my activity with ActivityWatch
[plugins.aw-watcher-vim]
git = "activitywatch/aw-watcher-vim"
rev = "4ba86d05a940574000c33f280fd7f6eccc284331"

[plugins.supermaven-nvim]
git = "supermaven-inc/supermaven-nvim"
rev = "07d20fce48a5629686aefb0a7cd4b25e33947d50"

[plugins."oxocarbon.nvim"]
git = "nyoom-engineering/oxocarbon.nvim"
rev = "004777819ba294423b638a35a75c9f0c7be758ed"

[treesitter]
auto_install = true
auto_highlight = "all"

[treesitter.parser_map]
mdx = "markdown"

[config]
colorscheme = "oxocarbon"

[bundles]

lsp.items = [
  "nvim-lspconfig",
  "mason.nvim",
]

setup.items = [
  "guess-indent.nvim",
  "supermaven-nvim"
]
