[plugins]

# Plugin manager
"rocks.nvim" = "2.36.0"
"rocks-config.nvim" = "2.1.4"
"rocks-treesitter.nvim" = "scm"
"rocks-git.nvim" = "2.0.0"

# Colorscheme
"kanagawa.nvim" = "scm"

# Find all the things
"telescope.nvim" = "scm"

# Generate docstrings
neogen = "2.17.1"

# Various utility mini-plugins
"mini.nvim" = "scm"

# The best git UI
neogit = "1.0.0"

# Note taking in neovim
neorg = "9.0.2"

# LSP

## Language server management
nvim-lspconfig = "0.1.8"
"mason.nvim" = "1.10.0"
"mason-lspconfig.nvim" = "1.29.0"

## Snippets
luasnip = "2.3.0"
cmp_luasnip = "scm"

## Formatting
"conform.nvim" = "6.0.0"

## Better UI for LSP actions
"dressing.nvim" = "2.2.2"

# Best task runner
"overseer.nvim" = "1.4.0"

# Treesitter parsers
tree-sitter-toml = "scm"
tree-sitter-query = "scm"
tree-sitter-go = "scm"
tree-sitter-markdown = "scm"
tree-sitter-lua = "scm"
tree-sitter-vimdoc = "scm"
tree-sitter-comment = "scm"
tree-sitter-elixir = "scm"
tree-sitter-svelte = "scm"
tree-sitter-typescript = "scm"
tree-sitter-javascript = "scm"
tree-sitter-css = "scm"
tree-sitter-just = "scm"
tree-sitter-gomod = "scm"
tree-sitter-markdown_inline = "scm"
tree-sitter-glsl = "scm"


# Autocompletion
cmp-nvim-lsp = "scm"

[plugins.nvim-cmp]
git = "hrsh7th/nvim-cmp"

# Automatic indentation
[plugins.indent-o-matic]
git = "Darazaki/indent-o-matic"
rev = "4d11e98f523d3c4500b1dc33f0d1a248a4f69719"

# Track my activity with ActivityWatch
[plugins.aw-watcher-vim]
git = "ActivityWatch/aw-watcher-vim"
rev = "4ba86d05a940574000c33f280fd7f6eccc284331"

# AI code completions
[plugins.supermaven-nvim]
git = "supermaven-inc/supermaven-nvim"
config = {}
rev = "d71257f431e190d9236d7f30da4c2d659389e91f"

# Edit my dotfiles which are managed by chezmoi
[plugins."chezmoi.vim"]
git = "alker0/chezmoi.vim"
rev = "10f2692791b5e512a2c1bb4dc560b42ca5bf71fd"

# Temporarily reqired by neorg
[plugins.nvim-treesitter]
git = "nvim-treesitter/nvim-treesitter"
rev = "v0.9.2^{}"
branch = "main"

[treesitter]
auto_install = true

[config]
colorscheme = "kanagawa"

[bundles]

lsp.items = [
  "nvim-lspconfig",
  "mason.nvim",
  "mason-lspconfig.nvim",
  "nvim-cmp",
  "cmp-nvim-lsp",
  "luasnip",
  "cmp_luasnip",
  "conform.nvim"
]
