[plugins]

# Plugin manager
"rocks.nvim" = "2.40.2"
"rocks-config.nvim" = "3.0.0"
"rocks-treesitter.nvim" = "1.1.3"
"rocks-git.nvim" = "2.3.1"

# Colorscheme
"kanagawa.nvim" = "scm"

# Find all the things
"telescope.nvim" = "scm"

# Generate docstrings
neogen = "2.19.4"

# Various utility mini-plugins
"mini.nvim" = "scm"

# The best git UI
neogit = "1.0.0"

# Note taking in neovim
neorg = "9.1.1"

# LSP

## Language server management
nvim-lspconfig = "1.0.0"
"mason.nvim" = "1.10.0"
"mason-lspconfig.nvim" = "1.31.0"

## Formatting
"conform.nvim" = "8.1.0"

## Better UI for LSP actions
"dressing.nvim" = "3.0.0"

# Automatic indentation
"guess-indent.nvim" = "scm"

# Best task runner
"overseer.nvim" = "1.4.0"

# Treesitter parsers
nvim-treesitter-legacy-api = "0.9.2"
tree-sitter-markdown = "scm"
tree-sitter-typescript = "scm"
tree-sitter-javascript = "scm"
tree-sitter-markdown_inline = "scm"
tree-sitter-ecma = "scm"
tree-sitter-python = "scm"
tree-sitter-gitignore = "scm"
tree-sitter-fish = "scm"
tree-sitter-html = "scm"
tree-sitter-jsdoc = "scm"
tree-sitter-toml = "scm"
tree-sitter-julia = "scm"
tree-sitter-bash = "scm"
tree-sitter-go = "scm"
tree-sitter-editorconfig = "scm"
tree-sitter-json = "scm"
tree-sitter-yaml = "scm"
tree-sitter-just = "scm"
tree-sitter-gitcommit = "scm"
tree-sitter-comment = "scm"
tree-sitter-ini = "scm"
tree-sitter-glsl = "scm"
tree-sitter-xml = "scm"
tree-sitter-css = "scm"
tree-sitter-jsonc = "scm"
tree-sitter-dockerfile = "scm"
tree-sitter-make = "scm"
tree-sitter-sql = "scm"
tree-sitter-gosum = "scm"
tree-sitter-csv = "scm"

# Track my activity with ActivityWatch
[plugins.aw-watcher-vim]
git = "activitywatch/aw-watcher-vim"
rev = "4ba86d05a940574000c33f280fd7f6eccc284331"

[plugins.supermaven-nvim]
git = "supermaven-inc/supermaven-nvim"
rev = "40bde487fe31723cdd180843b182f70c6a991226"

[treesitter]
auto_install = true
auto_highlight = "all"

[config]
colorscheme = "kanagawa"

[bundles]

lsp.items = [
  "nvim-lspconfig",
  "mason.nvim",
  "mason-lspconfig.nvim",
  "conform.nvim"
]

setup.items = [
  "guess-indent.nvim",
  "supermaven-nvim"
]
