[plugins]

# Plugin manager
"rocks.nvim" = "2.37.1"
"rocks-config.nvim" = "2.2.0"
"rocks-treesitter.nvim" = "1.0.3"
"rocks-git.nvim" = "2.0.1"

# Colorscheme
"kanagawa.nvim" = "scm"

# Find all the things
"telescope.nvim" = "scm"

# Generate docstrings
neogen = "2.19.4"

# Various utility mini-plugins
"mini.nvim" = "scm"

# The best git UI
neogit = "1.0.0"

# Note taking in neovim
neorg = "9.1.1"

# LSP

## Language server management
nvim-lspconfig = "0.1.8"
"mason.nvim" = "1.10.0"
"mason-lspconfig.nvim" = "1.30.0"

## Formatting
"conform.nvim" = "7.1.0"

## Better UI for LSP actions
"dressing.nvim" = "2.2.2"

# Automatic indentation
"guess-indent.nvim" = "scm"

# Best task runner
"overseer.nvim" = "1.4.0"

# Treesitter parsers
tree-sitter-markdown = "0.0.2"
tree-sitter-typescript = "0.0.3"
tree-sitter-javascript = "0.0.2"
tree-sitter-markdown_inline = "0.0.2"
tree-sitter-ecma = "0.0.2"
tree-sitter-python = "0.0.3"
nvim-treesitter-legacy-api = "0.9.2"
tree-sitter-gitignore = "0.0.2"
tree-sitter-fish = "0.0.2"
tree-sitter-html = "0.0.3"
tree-sitter-jsdoc = "0.0.2"
tree-sitter-toml = "0.0.2"

# Track my activity with ActivityWatch
[plugins.aw-watcher-vim]
git = "ActivityWatch/aw-watcher-vim"
rev = "4ba86d05a940574000c33f280fd7f6eccc284331"

# AI code completions
[plugins.supermaven-nvim]
git = "supermaven-inc/supermaven-nvim"
rev = "d71257f431e190d9236d7f30da4c2d659389e91f"

# Edit my dotfiles which are managed by chezmoi
[plugins."chezmoi.vim"]
git = "alker0/chezmoi.vim"
rev = "10f2692791b5e512a2c1bb4dc560b42ca5bf71fd"

[plugins."care.nvim"]
git = "max397574/care.nvim"
rev = "main"

[plugins.care-lsp]
git = "max397574/care-lsp"
rev = "main"

[treesitter]
auto_install = true
auto_highlight = "all"

[config]
colorscheme = "kanagawa"

[bundles]

lsp.items = [
  "nvim-lspconfig",
  "mason.nvim",
  "mason-lspconfig.nvim",
  "care.nvim",
  "care-lsp",
  "conform.nvim"
]

setup.items = [
 "supermaven-nvim",
 "guess-indent.nvim"
]
